name: GitHub Pages CI/CD
on:
  push:
    branches: [master]
jobs:
  Deploy-GitHub-Pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run : git config user.name github-actions
      - run : git config user.email github-actions@github.com
      - uses: borales/actions-yarn@v2.3.0
      - run: yarn install
      - uses: borales/actions-yarn@v2.3.0
      - run: yarn build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
